name: Setup YouTube Uploader
description: Setup/Install YouTube Uploader for GitHub Actions
branding:
  icon: upload
  color: red
inputs:
  client_secrets:
    description: client_secrets.json file encoded in base64
    required: true
  request_token:
    description: request.token file encoded in base64
    required: true
  version:
    description: YouTube Uploader version
    default: latest
  token:
    description: GitHub token to avoid API rate limiting
    default: ${{ github.token }}
    
runs:
  using: composite
  steps:
    - name: Get YouTube Uploader version for Unix-like
      id: version-unix-like
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/version/Unix-like.sh
      env:
        version: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ inputs.token }}
        
    - name: Get YouTube Uploader version for Windows
      id: version-windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: '& $env:GITHUB_ACTION_PATH\scripts\version\Windows.ps1'
      env:
        version: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ inputs.token }}
        
    - name: Download YouTube Uploader for Unix-like
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      working-directory: ${{ runner.temp }}
      run: $GITHUB_ACTION_PATH/scripts/download/Unix-like.sh
      env:
        version: ${{ steps.version-unix-like.outputs.version }}
        
    - name: Download YouTube Uploader for Windows
      if: runner.os == 'Windows'
      shell: pwsh
      working-directory: ${{ runner.temp }}
      run: '& $env:GITHUB_ACTION_PATH\scripts\download\Windows.ps1'
      env:
        version: ${{ steps.version-windows.outputs.version }}
        
    - name: Install YouTube Uploader on tool cache
      uses: AnimMouse/tool-cache@v1
      with:
        folder_name: youtubeuploader
        
    - name: Sign in to YouTube Uploader on Unix-like
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/sign-in/Unix-like.sh
      env:
        client_secrets: ${{ inputs.client_secrets }}
        request_token: ${{ inputs.request_token }}
        
    - name: Sign in to YouTube Uploader on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: '& $env:GITHUB_ACTION_PATH\scripts\sign-in\Windows.ps1'
      env:
        client_secrets: ${{ inputs.client_secrets }}
        request_token: ${{ inputs.request_token }}