name: Setup YouTube Uploader
description: Setup/Install YouTube Uploader for GitHub Actions
branding:
  icon: upload
  color: red
inputs:
  client_secrets:
    description: client_secrets.json file encoded in base64
    required: true
  request_token:
    description: request.token file encoded in base64
    required: true
    
runs:
  using: composite
  steps:
    - name: Download YouTube Uploader for Linux
      if: runner.os == 'Linux'
      shell: bash
      working-directory: ${{ runner.temp }}
      run: $GITHUB_ACTION_PATH/scripts/download/Linux.sh
      
    - name: Download YouTube Uploader for Windows
      if: runner.os == 'Windows'
      shell: pwsh
      working-directory: ${{ runner.temp }}
      run: '& $env:GITHUB_ACTION_PATH\scripts\download\Windows.ps1'
      
    - name: Download YouTube Uploader for macOS
      if: runner.os == 'macOS'
      shell: bash
      working-directory: ${{ runner.temp }}
      run: $GITHUB_ACTION_PATH/scripts/download/macOS.sh
      
    - name: Install YouTube Uploader on tool cache
      uses: AnimMouse/tool-cache@v1
      with:
        folder_name: youtubeuploader
        
    - name: Sign in to YouTube Uploader on Unix-like
      if: runner.os == 'Linux'
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/sign-in/Unix-like.sh
      env:
        client_secrets: ${{ inputs.client_secrets }}
        request_token: ${{ inputs.request_token }}
        
    - name: Sign in to YouTube Uploader on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: '& $env:GITHUB_ACTION_PATH\scripts\sign-in\Windows.ps1'
      env:
        client_secrets: ${{ inputs.client_secrets }}
        request_token: ${{ inputs.request_token }}