name: Setup YouTube Uploader
description: Setup/Install YouTube Uploader for GitHub Actions
branding:
  icon: upload
  color: red
inputs:
  client_secrets:
    description: client_secrets.json file encoded in Base64
    default: false
  request_token:
    description: request.token file encoded in Base64
    default: false
  version:
    description: YouTube Uploader version
    default: latest
  token:
    description: GitHub token to avoid API rate limiting
    default: ${{ github.token }}
    
runs:
  using: composite
  steps:
    - name: Get YouTube Uploader version for Unix-like
      id: version-unix-like
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/version/Unix-like.sh
      env:
        version: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ inputs.token }}
        
    - name: Get YouTube Uploader version for Windows
      id: version-windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: '& $env:GITHUB_ACTION_PATH\scripts\version\Windows.ps1'
      env:
        version: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ inputs.token }}
        
    - name: Restore YouTube Uploader cache
      id: cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ runner.tool_cache }}/youtubeuploader
        key: youtubeuploader-${{ steps.version-unix-like.outputs.version || steps.version-windows.outputs.version }}-${{ runner.os }}
        
    - name: Download YouTube Uploader for Unix-like
      if: (runner.os == 'Linux' || runner.os == 'macOS') && ! steps.cache.outputs.cache-hit
      shell: bash
      working-directory: ${{ runner.temp }}
      run: $GITHUB_ACTION_PATH/scripts/download/Unix-like.sh
      env:
        version: ${{ steps.version-unix-like.outputs.version }}
        
    - name: Download YouTube Uploader for Windows
      if: runner.os == 'Windows' && ! steps.cache.outputs.cache-hit
      shell: pwsh
      working-directory: ${{ runner.temp }}
      run: '& $env:GITHUB_ACTION_PATH\scripts\download\Windows.ps1'
      env:
        version: ${{ steps.version-windows.outputs.version }}
        
    - name: Install YouTube Uploader on tool cache
      uses: AnimMouse/tool-cache@v1
      with:
        folder_name: youtubeuploader
        cache_hit: ${{ steps.cache.outputs.cache-hit }}
        
    - name: Sign in to YouTube Uploader on Unix-like
      if: (runner.os == 'Linux' || runner.os == 'macOS') && (inputs.client_secrets != 'false' && inputs.request_token != 'false')
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/sign-in/Unix-like.sh
      env:
        client_secrets: ${{ inputs.client_secrets }}
        request_token: ${{ inputs.request_token }}
        
    - name: Sign in to YouTube Uploader on Windows
      if: runner.os == 'Windows' && (inputs.client_secrets != 'false' && inputs.request_token != 'false')
      shell: pwsh
      run: '& $env:GITHUB_ACTION_PATH\scripts\sign-in\Windows.ps1'
      env:
        client_secrets: ${{ inputs.client_secrets }}
        request_token: ${{ inputs.request_token }}
        
    - name: Save YouTube Uploader cache
      if: '! steps.cache.outputs.cache-hit'
      uses: actions/cache/save@v4
      with:
        path: ${{ runner.tool_cache }}/youtubeuploader
        key: youtubeuploader-${{ steps.version-unix-like.outputs.version || steps.version-windows.outputs.version }}-${{ runner.os }}